feat: added directors
iluxa-152436/java-filmorate pull request #16
Opened 2023-06-12 14:42 UTC by Terofitus

2023-06-12 18:31 UTC, iluxa-152436 requested changes
Есть пара вопросов на обсуждение и замечаний

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_director (
Два раза создаем таблицу  film_director, надо убрать одно лишнее создание

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getGenres() != null) {
мне кажется, что проверка на null тут лишняя, т.к. при создании экземпляра Film уже есть проверка жанра на пустоту, и если оно пусто - создается дефолтный экземпляр списка жанров для этого фильма - пустой список жанров. Вот проверка при создании фильма:  
this.genres = Objects.requireNonNullElseGet(genres, HashSet::new);
this.directors = Objects.requireNonNullElseGet(directors, HashSet::new);

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.likes = Objects.requireNonNullElseGet(likes, HashSet::new);
нам надо хранить лайки пользователей в фильме? я считал их отдельной сущностью. А в фильме хранились только атрибуты/реквизиты фильма.
И придется изменять в самом фильме лайки, если они меняются в хранилище лайков

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (film.getGenres() != null) {
аналогично надо подумать над обязательностью этой проверки, если у нас нельзя создать фильм с null в полях directors  и genres

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DbDirectorStorage.java
> +                if (userLikeId != 0) {
можно будет не заполнять, если брать лайки из сервиса лайков

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +import ru.yandex.practicum.filmorate.exception.DirectorNotFoundException;
тут повтор импорта, можно убрать

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (film.getDirectors() != null) {
аналогично по режиссерам, если при создании фильма уже создадим пустую коллекцию, можно будет на null вообще не проверять. Null проще не допустить, чем потом проверять на него))

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/resources/schema.sql
> +  name varchar(40)
Я бы тут добавил NOT NULL. Так точно не создадут случайно режиссера с пустым ФИО

2023-06-12 18:31 UTC, iluxa-152436 commented on src/test/java/ru/yandex/practicum/filmorate/controller/DirectorControllerTest.java
> +        MvcResult result = mockMvc.perform(post("/directors").contentType(MediaType.APPLICATION_JSON)
круто, я не использовал моки еще. ушел изучать вопрос)))

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/exception/FindDirectorException.java
а в чем принципиальное отличие от  DirectorNotFoundException? нам точно нужны две ошибки про ошибку поиска директора?

2023-06-12 18:31 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return films.stream().sorted(Comparator.comparingInt((Film film) -> film.getLikes().size())
если искать по общей базе лайков то можно просто добавить метод в сервис лайков и в реализацию хранилки лайков. 
Что-нибудь такое: `int getNumberOfLikesByFilmId(int filmId) {...}`

Или так получать уже список id фильмов, отсортированных по количеству лайков: `List<Integer> getSortedFilmIdsByLikes(List <Integer> filmIds){...} ` 

Т.е. во втором варианте в сервисе фильмов FilmService получаем список id фильмов режиссера из вызова метода DirectorService, отдаем список id фильмов в метод сервиса лайков LikeService, получаем в ответ список id фильмов, отсортированный по количеству лайков , собираем список фильмов в этом порядке внутри FilmService.

2023-06-14 16:38 UTC, Terofitus commented on src/main/java/ru/yandex/practicum/filmorate/exception/FindDirectorException.java
Ввел 2 исключения потому что в случае DirectorNotFoundException должен возвращаться статус 404, а в случае создания режиссера, если такой уже есть в базе, как я понимаю, должен быть возвращен статус 400 bad request, следовательно в ExceptionHandler должны обрабатываться разными методами. Из тестов постмана как необходимость не следует, но следую логике думаю он нужен. В общем оставляю на ваше усмотрение)

2023-06-14 18:19 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/exception/FindDirectorException.java
вроде все тесты из постмана проходят с 404 при поиске несуществующего, а на создание дублей не нашел тест
А в хорошем варианте для реальных проектов при POST должна работать идемпотентность, когда дубль не создается, а возвращается модель уже созданного ранее объекта

2023-06-14 20:31 UTC, Terofitus commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getGenres() != null) {
В этом, как и в других случаях, без данных проверок тесты падают с NullPointerException в тех местах, где были эти проверки. Могу разве что предположить, что это связанно с маппингом фильмов из json, точно не знаю, но похоже бы при маппинге объект строиться по типу билдера и в итоге Objects.requireNonNullElseGet не отрабатывает.

2023-06-14 20:48 UTC, Terofitus commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return films.stream().sorted(Comparator.comparingInt((Film film) -> film.getLikes().size())
В итоге реализацию метода getNumberOfLikesByFilmId разместил в DbFilmStorage, так как иначе, добавляя зависимость в виде LikeService в FilmService создается циклическая зависимость, которую разрешить можно или через ленивую инициализацию, или через внедрение зависимости через сеттеры, или через рефакторинг. Последний вариант показался самым простым и я не увидел причины усложнять ситуацию)

2023-06-14 21:06 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getGenres() != null) {
Возможно оно падает из-за @NoArgsConstructor, конструктор без параметров используется как дефолтный.
Ты добавил его только для тестов или конструктор без параметров требуется по задаче?

2023-06-14 21:22 UTC, iluxa-152436 approved these changes
ок, но над проверкой на null и конструкторами без аргументов я бы еще подумал

2023-06-15 15:52 UTC, RakhmaIs approved these changes

2023-06-15 16:08 UTC, merged