feat - implemented common friends functionality
iluxa-152436/java-filmorate pull request #17
Opened 2023-06-13 07:22 UTC by seymirpro

2023-06-13 12:06 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        try {
Какого рода ошибки тут отлавливаем?

2023-06-13 12:06 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        System.out.println("userId = " + userId);
может это убрать в `log.debug()`
на тестах запускается режим дебаг и идет вывод в консоль

2023-06-13 12:06 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (film.getGenres() != null && !film.getGenres().isEmpty()) {
поле genres не может быть пустым в фильме, оно заполняется при создании экземпляра Film `this.genres = Objects.requireNonNullElseGet(genres, HashSet::new);`

2023-06-13 12:06 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public List<Film> getCommonFilms(Integer userId, Integer friendId) {
Можешь добавить тест на проверку функционала?

2023-06-13 13:13 UTC, RakhmaIs requested changes

2023-06-13 13:13 UTC, RakhmaIs commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                System.out.println("Inside cycle");
Если использовал для отладки думаю это можно удалить в конечном варианте.

2023-06-13 13:13 UTC, RakhmaIs commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        System.out.println("friendId = " + friendId);
Это тоже наверно лишнее в конечном варианте, если использовал для отладки можно удалить.

2023-06-14 08:12 UTC, seymirpro commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        System.out.println("userId = " + userId);
убрал, для дебага использовал)

2023-06-14 08:13 UTC, seymirpro commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (film.getGenres() != null && !film.getGenres().isEmpty()) {
по какой то причине, как раз таки у меня с нуллом падал, хотя да, обратил внимание что ты заполняешь по дефолту. Я оставил, иначе у меня локально тесты падали

2023-06-14 08:21 UTC, seymirpro commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        try {
когда дебажил оставил, убрал сейчас)

2023-06-14 08:37 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (film.getGenres() != null && !film.getGenres().isEmpty()) {
если речь про локальные тесты, которые написаны в коде надо посмотреть какой конструктор используется)) возможно используется дефолтный конструктор класса Film я его убирал.

2023-06-14 08:40 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@NoArgsConstructor
Вот эта штука может приводить к NPE в жанрах

2023-06-14 08:47 UTC, seymirpro commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@NoArgsConstructor
оке, поправил

2023-06-14 08:48 UTC, seymirpro commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        if (film.getGenres() != null && !film.getGenres().isEmpty()) {
локальные json тесты в постмане падали у меня) в целом, если критично, могу убрать эту проверку

2023-06-14 10:06 UTC, seymirpro commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@NoArgsConstructor
Я убрал эту аннотацию, добавил ручками дефолтовый конструктор, но при этом там же задаю жанры. Если так, то работает. Создал дефолтовый, потому что тесты падали для FilmControllerTest без дефолтового конструктора

2023-06-14 20:53 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id,
Эти новые конструкторы только для тестов добавлены? Если, да, то лучше тесты поправить на полный конструктор

2023-06-14 20:53 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getCommonFilms(@RequestParam String userId, @RequestParam String friendId) {
Попробуй прямо в контроллере получить из параметров int, чтобы потом в сервисе не заниматься парсингом строки

2023-06-14 20:53 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getCommonFilms(String userId, String friendId) {
проще сразу в контроллере получить int и передавать в качестве параметров два int

2023-06-15 08:48 UTC, RakhmaIs approved these changes

2023-06-15 09:25 UTC, iluxa-152436 approved these changes
ок

2023-06-15 11:23 UTC, merged