Controllers films users
iluxa-152436/java-filmorate pull request #5
Opened 2023-04-13 13:29 UTC by iluxa-152436

Добавлены основные классы, сервисы, контроллеры, тесты

2023-04-13 14:32 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе

2023-04-13 14:32 UTC, Frilock commented on pom.xml
> +			<version>2.0.1.Final</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-04-13 14:32 UTC, Frilock commented on pom.xml
> +			<version>1.18.26</version>
Версия lombok кстати в parent - 		<artifactId>spring-boot-starter-parent</artifactId> уже есть, можно ее не указывать

2023-04-13 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidateFilmException e) {
Не замечание, но на всякий -https://struchkov.dev/blog/ru/exception-handling-controlleradvice/

2023-04-13 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    int id;
А почему модификатор отсуствует?

2023-04-13 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Getter
А зачем тут getter И setter?

2023-04-13 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(FIRST_RELEASE_DATE)) {
У вас нет валидации вроде что дата не null, так что тут тогда тоже это надо проверить

2023-04-13 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    int id;
Модификатор

2023-04-13 14:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Можно обьединить 2 проверки эти в 1, используя библиотеку Apache common 3, StringUtils.isBlank

2023-04-13 14:32 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film = new Film(1,
У вас в нескольких местах 1 объект создается, вынесете его в отдельный метод

2023-04-14 12:35 UTC, iluxa-152436 commented on pom.xml
> +			<version>2.0.1.Final</version>
поправил

2023-04-14 12:35 UTC, iluxa-152436 commented on pom.xml
> +			<version>1.18.26</version>
Поправил

2023-04-14 12:37 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidateFilmException e) {
Прочитал, понял, вынес обработку ошибок валидации в отдельный класс. Теперь на вызов API приходит понятная ошибка с описанием.

2023-04-14 12:37 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    int id;
Добавил

2023-04-14 12:37 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Getter
Да, лишние. Убрал, поменял тесты.

2023-04-14 12:38 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(FIRST_RELEASE_DATE)) {
Добавил

2023-04-14 12:38 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    int id;
Добавил

2023-04-14 12:39 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Переписал

2023-04-14 12:39 UTC, iluxa-152436 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film = new Film(1,
Вынес в отдельный метод

2023-04-14 15:43 UTC, Frilock approved these changes
Принято

2023-04-14 16:01 UTC, merged