Add database
iluxa-152436/java-filmorate pull request #8
Opened 2023-05-24 18:44 UTC by iluxa-152436

Добавлено хранение в БД

2023-05-24 19:58 UTC, Frilock requested changes
Добрый вечер, написал ряд комментариев. Жду новую версию.

2023-05-24 19:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Как вариант, можно инициализировать прям тут, чтобы избежать лишних проверок на нул

2023-05-24 19:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +@Slf4j
Аннотация есть, а логирование отсутствует

2023-05-24 19:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaRatingService.java
> +@Slf4j
аналогично

2023-05-24 19:58 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        } catch (NullPointerException e) {
В каком случае NPE получим? NPE не нужно проверять, его нужно не допускать

2023-05-24 19:58 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_genre (
Давайте приведем скрипт к виду, как при создании таблицы films

2023-05-24 19:58 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/storage/DbFilmStorageTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Должно работать и без (onConstructor_ = @Autowired)

2023-05-24 19:58 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/storage/DbFriendStorageTest.java
> +    @Order(1)
Хочется чтобы вы отказались от аннотации order - порядок тестов не должен влиять на их прохождение

2023-05-25 10:35 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
добавил инициализацию в конструктор, при получении null создаю пустой Set

2023-05-25 10:36 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +@Slf4j
добавил логирование

2023-05-25 10:36 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaRatingService.java
> +@Slf4j
добавил логирование

2023-05-25 10:37 UTC, iluxa-152436 commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +        } catch (NullPointerException e) {
переписал обработчик по получению результата

2023-05-25 10:37 UTC, iluxa-152436 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_genre (
отформатировал скрипты

2023-05-25 10:37 UTC, iluxa-152436 commented on src/test/java/ru/yandex/practicum/filmorate/storage/DbFilmStorageTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Точно)) работает

2023-05-25 10:38 UTC, iluxa-152436 commented on src/test/java/ru/yandex/practicum/filmorate/storage/DbFriendStorageTest.java
> +    @Order(1)
Понял, да, переделал

2023-05-25 20:33 UTC, Frilock approved these changes
На данном этапе принято, хотя в ряде мест можно чуть лучше. В дальнейшем доработаем.

2023-05-25 20:33 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres;
Зачем так сложно? Я имел ввиду просто private Set<Genre> genres = new HashSet<>():

2023-06-06 15:02 UTC, merged